# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  deploy:
    docker:
      - image: docker/compose:1.29.1
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Building
          command: |
            docker build -t udagram-api-feed ./udagram-api-feed
            docker build -t udagram-api-user ./udagram-api-user
            docker build -t udagram-frontend ./udagram-frontend
            docker build -t udagram-reverseproxy ./udagram-reverseproxy
      - run: 
          name: Tagging
          command: |
            docker tag udagram-api-feed lequangbao1/udagram-api-feed:lastest
            docker tag udagram-api-user lequangbao1/udagram-api-user:lastest
            docker tag udagram-frontend lequangbao1/udagram-frontend:eks
            docker tag udagram-reverseproxy lequangbao1/udagram-reverseproxy:lastest
      # After a command fails, no further job steps will be executed.
      - run:
          name: Deploying
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push lequangbao1/udagram-api-feed:lastest
            docker push lequangbao1/udagram-api-user:lastest
            docker push lequangbao1/udagram-frontend:eks
            docker push lequangbao1/udagram-reverseproxy:lastest
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy
