apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-user
  name: api-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-user
  template:
    metadata:
      labels:
        app: api-user
    spec:
      containers:
        - image: lequangbao1/udagram-api-user:lastest
          name: api-user
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2048Mi"
              cpu: "500m"
          volumeMounts:
            - name: aws-secret
              mountPath: "/root/.aws/"
              readOnly: true
          envFrom:
            - configMapRef:
                name: env-config
            - secretRef:
                name: env-secret
      restartPolicy: Always
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret
